spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-service-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-service-test
